### ISSUE TITLE
Encryption error with PS 1.6.1.5

### ISSUE THREAD

**Issue by jpfox** [alma/alma-installments-prestashop#179]
In this version of Prestashop, constant _RIJNDAEL_KEY_ and _RIJNDAEL_IV_ or not defined.

So, api keys and module configuration can't be saved.

Where can I define them ? and with which values ?

Or is it possible to downgrade to a compatible version ? If so, which one ?

Message on alma module configuration page :
```
Notice à la ligne 90 du fichier .../modules/alma/lib/Utils/EncryptionHelper.php
[8] Use of undefined constant _RIJNDAEL_KEY_ - assumed '_RIJNDAEL_KEY_'

Notice à la ligne 90 du fichier .../modules/alma/lib/Utils/EncryptionHelper.php
[8] Use of undefined constant _RIJNDAEL_IV_ - assumed '_RIJNDAEL_IV_'

Warning à la ligne 68 du fichier .../classes/Rijndael.php
[2] mcrypt_decrypt(): Key of size 14 not supported by this algorithm. Only keys of sizes 16, 24 or 32 supported
```

Thanks for your help

**Comment by Benjamin-Freoua-Alma** [comment]
Hello @jpfox,

The keys `RIJNDAEL_KEY ` and `RIJNDAEL_IV` are normally in the `/config/settings.inc.php` file.
This version of Prestashop use normally the `Rijndael` lib for encryption.
Can you see if in your back-office, the Algorithm is well enabled ? In Advanced Parameters > Performance > CIPHERING.
Or you can try to add these keys in the file `/config/settings.inc.php` for fix your issue.
We can help you to find a solution for improve our module in your case. Or if you prefer downgrade, the last version without Encryption, you can install the version [2.11.0](https://github.com/alma/alma-installments-prestashop/releases/tag/v2.11.0)

Thanks for you understanding
