### ISSUE TITLE
Compatibility with composer

### ISSUE THREAD

**Issue by gross-nvs** [alma/alma-installments-prestashop#267]
Hello,

Your module use composer but the composer file and this repository are not suited for installing the module on a prestashop via composer.

Here is a list of the offending point that prevent such usage:

- `prestashop/autoindex` must be required as a development dependency
- `type` must be `prestashop-module` instead of `library` in the composer definition
- `lib/smarty.php` is autoloaded but relies on a define and a class check that are not available on autoload initialization (can be moved via an old-school `require_once` or a 1.5+ compatible hook like `actionDispatcher`)
- Add `"extra": { "installer-name": "alma" },` to the composer json because the repository name doesn't match the module name
- The module and the composer files are not at the root of the repository

Please consider making your module installable via composer, it make versioning easier for agencies managing versions outside the prestashop markeplace, it also allow having someone's prestashop into a git repository without having the module commited into the tree and allow strict version management.

Otherwise, kudos for making a PS 1.5+ compatible module with such a clean code base, definitely not a priority for many of your competitors.

Thanks!

EDIT: adding missing info

**Comment by Benjamin-Freoua-Alma** [comment]
Hello @gross-nvs,
Thanks for your suggestions.
We will explore it and we will update it if it's relevant for our module.
Thanks again for your assessment
