### ISSUE TITLE
Error message (Alma encountered an error when fetching merchant status, please check your api keys or retry later.)

### ISSUE THREAD

**Issue by catlynx** [alma/alma-installments-prestashop#289]
Hello,

Since the beginning of the year, we had this error message (Alma encountered an error when fetching merchant status, please check your api keys or retry later.), same error when updating.

After uninstall and reinstall, we had always the same error message but now the api keys are not saved.

Prestashop version : v1.7.7.4
Module version : Alma v3.1.3
Debug mode : no error message.
Server log : no error message.

Thanks in advance

**Comment by Benjamin-Freoua-Alma** [comment]
Hello @catlynx ,

Thank you for taking the time to leave a comment regarding your experience with Alma.

We are sincerely sorry to read that it did not live up to your expectations.

In order for us to assist you as quickly as possible, could you please write to us at [support@getalma.eu] giving your contact details (name of your Alma account, email) ? A member of our team will contact you very quickly to assist you.

Thank you very much and have a nice day.

Best regards,

The Alma team
