### ISSUE TITLE
Critical error with the version 4.1.1

### ISSUE THREAD

**Issue by maofree** [alma/alma-installments-prestashop#505]
Hi
I report to you a critical error after the upgrade to 4.1.1 from 4.0.1
the module doesn't work anymore
it is not possible to reinstall it
it added some javascript errors in the front-office
it was not possible to enter the module configuration page, it gave me an error

![1](https://github.com/alma/alma-installments-prestashop/assets/653230/18b04747-cf44-41c2-b63f-72e8d91fa3ed)
![2](https://github.com/alma/alma-installments-prestashop/assets/653230/cf57b040-ab55-472a-b2db-8a12d04d1a4c)

this is the error

Impossibile Install il modulo alma. The "alma.ps_accounts_installer" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

this the website, made with prestashop 8.1.7 and php 8.1

at this moment I've removed the module

I can give you the access to the website
bye

**Comment by maofree** [comment]
I reinstalled version 4.0.1 and everything worked fine again.
so you have added errors in the latest versions

**Comment by LaqueP** [comment]
Same bug here.
Prestashop 8.1.7
PHP: 8.1

**Comment by FranceBe** [comment]
Hello, t
hank you for reporting this issue, we'll let you know when fixed 🙏

**Comment by Benjamin-Freoua-Alma** [comment]
Hello @maofree, @LaqueP 
We have just published a new release [4.1.2](https://github.com/alma/alma-installments-prestashop/releases/tag/v4.1.2) with the fix about "alma.ps_accounts_installer".
It should be published on the market place by tomorrow.
Thank you for reporting this issue and for your understanding. 🙏
