### ISSUE TITLE
PHP Fatal error:  Declaration of Alma\PrestaShop\Factories\LinkFactory::getImageLink($name, $ids, $type = null) 

### ISSUE THREAD

**Issue by LaqueP** [alma/alma-installments-prestashop#513]
PHP Fatal error:  Declaration of Alma\PrestaShop\Factories\LinkFactory::getImageLink($name, $ids, $type = null) must be compatible with LinkCore::getImageLink($name, $ids, $type = null, string $extension = 'jpg') in /home/admin/domains/entorno.nestdream.com/public_html/modules/alma/lib/Factories/LinkFactory.php on line 36\n

**Comment by Benjamin-Freoua-Alma** [comment]
Hello @LaqueP 
Thanks you for reporting this issue.
Can you tell us more about how you came across this error?

**Comment by LaqueP** [comment]
Hi @Benjamin-Freoua-Alma ;
Navegating across the website it returns this fatal error.

Prestasho: 8.1.7
Php 8.1

We turn back to version 4.0.1 to solve the problem

**Comment by Benjamin-Freoua-Alma** [comment]
Thanks for your return @LaqueP 
We fixed it and we plan a new release in a few days 🙏
