### ISSUE TITLE
502 Bad Gateway in order page

### ISSUE THREAD

**Issue by catlynx** [alma/alma-installments-prestashop#66]
Hi,

We are getting "502 Bad Gateway" when accessing the order page (front-end).
It happens on some clients and works on others.

PHP error log :
`FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to get property 'installmentsCount' of non-object in site/modules/alma/lib/API/EligibilityHelper.php on line 106PHP`

Notes : 
The module worked perfectly before this issue.
I updated the module and the error is still there.

Prestashop version : 1.7.7.4
PHP version : 7.3

Thanks in advance

**Comment by Benjamin-Freoua-Alma** [comment]
Hi @catlynx,
Do you have enable CGI mode in Prestashop parameter?
Wouldn't the problem be on the server side?
We have not had any other reports of this kind and our installmentCount is always aggregated at this location.

![Capture d’écran 2022-01-18 à 17 29 55](https://user-images.githubusercontent.com/89775252/149978036-03cc2091-d31c-45e6-989d-ffe051450f85.png)
