### ISSUE TITLE
Bug when creating a new order (back-office)

### ISSUE THREAD

**Issue by catlynx** [alma/alma-installments-prestashop#67]
Hi,

When creating a manual order from the back-office and choosing ALMA as the payment method, the order is created but it shows an error. We cannot open the created order and shows the errors bellow.

Logs :

>Twig\Error\
>RuntimeError
>in src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/view.html.twig (line 82)
```
<div id="orderProductsOriginalPosition">
{% include '@PrestaShop/Admin/Sell/Order/Order/Blocks/View/products.html.twig' %}
</div>
{% include '@PrestaShop/Admin/Sell/Order/Order/Blocks/View/details.html.twig' %}
{{ renderhook('displayAdminOrderMain', {'id_order': orderForViewing.id}) }}
{% include '@PrestaShop/Admin/Sell/Order/Order/Blocks/View/payments.html.twig' %}
{{ renderhook('displayAdminOrderMainBottom', {'id_order': orderForViewing.id}) }
</div>
</div>
```

###############
>Alma\API\
>RequestError
>Not found
```
public function fetch($id)
{

$res = $this->request(self::PAYMENTS_PATH . "/$id")->get();
if ($res->isError()) {
throw new RequestError($res->errorMessage, null, $res);
}
return new Payment($res->json);
}
```

###############
>Payments->fetch('')
>in modules/alma/controllers/hook/DisplayRefundsHookController.php (line 69)
```
);
}
$paymentId = $orderPayment->transaction_id;
$payment = $alma->payments->fetch($paymentId);
if (is_callable('Media::getMediaPath')) {
$iconPath = Media::getMediaPath(_PS_MODULE_DIR_ . $this->module->name . '/views/img/logos/alma_tiny.svg')
} else {
$iconPath = $this->module->getPathUri() . '/views/img/logos/alma_tiny.svg';
```

Prestashop version : 1.7.7.4
PHP version : 7.3

Thanks

**Comment by Benjamin-Freoua-Alma** [comment]
Hi @catlynx,
Thank you for your issue.
We have not yet developed this feature.
But we have provided the information to the product team and they will work on defining a timeframe for this feature.

**Comment by catlynx** [comment]
Hi @Benjamin-Freoua-Alma 

Thank you for the response.
