### ISSUE TITLE
ErrorException with messageTrying to get property 'isEligible' of non-object

### ISSUE THREAD

**Issue by clotairer** [alma/alma-installments-prestashop#78]
Hi,

we have this error on our website on the checkout and the order confirmation page:

/CartController
ErrorException:
Uncaught exception 'ErrorException' with message 'Trying to get property 'isEligible' of non-object' in modules/alma/controllers/hook/DisplayShoppingCartFooterHookController.php:67

/OrderController
ErrorException:
Uncaught exception 'ErrorException' with message 'Trying to get property 'isEligible' of non-object' in modules/alma/controllers/hook/PaymentOptionsHookController.php:74

Could you please tell us how is it possible installment plans can return an iterable that content an inapropriate content (not a collection of object plan) ?

Version PS 1.7.7 last version of alma
Thank you.

**Comment by Benjamin-Freoua-Alma** [comment]
Hi @clotairer,
Thanks for reaching us. We are unable to reproduce your issue.
To allow us to dig further could you send an email to integrations@getalma.eu including this issue and your Alma merchant ID.
Best regards.

Benjamin
